"""DBMS ごとの差分。

SQL の本体は1つに保ち、方言による違い（プレースホルダ・主キーの書き方・
日付関数・例外の型）だけをここに閉じ込める。新しい DBMS を足す場合も
このファイルに1クラス増やすだけで済むようにしている。
"""

from __future__ import annotations

import re
import sqlite3
from abc import ABC, abstractmethod
from pathlib import Path
from typing import Any
from urllib.parse import urlparse

from .errors import DuplicateKeyError, ForeignKeyError

# マイグレーションの SQL 中で方言差を吸収するための差し込み記号
PK = "{{PK}}"
TODAY = "{{TODAY}}"
NOW = "{{NOW}}"


class Dialect(ABC):
    """1つの DBMS に対する差分の定義。"""

    name: str
    placeholder: str
    supports_returning: bool

    @abstractmethod
    def connect(self, target: str) -> Any:
        """ドライバの接続を開いて返す。"""

    @abstractmethod
    def substitutions(self) -> dict[str, str]:
        """マイグレーション SQL の差し込み記号に対する置換。"""

    @abstractmethod
    def in_transaction(self, raw: Any) -> bool:
        """トランザクションが開いているか。"""

    @abstractmethod
    def translate_error(self, error: Exception) -> Exception | None:
        """ドライバ固有の例外を共通の型に翻訳する。対象外なら None。"""

    def render(self, sql: str) -> str:
        """差し込み記号を置換し、プレースホルダを方言に合わせる。"""
        for token, replacement in self.substitutions().items():
            sql = sql.replace(token, replacement)
        if self.placeholder != "?":
            sql = _swap_placeholders(sql, self.placeholder)
        return sql


class SqliteDialect(Dialect):
    """既定。1ファイルで完結し、サーバーを持たない。"""

    name = "sqlite"
    placeholder = "?"
    supports_returning = False

    def connect(self, target: str) -> sqlite3.Connection:
        path = Path(target)
        if str(path.parent) not in ("", "."):
            path.parent.mkdir(parents=True, exist_ok=True)
        # Streamlit はセッションごとに別スレッドで動くため、接続は
        # セッション単位で作る前提で check_same_thread を外す。
        # isolation_level=None で暗黙トランザクションを切り、開始と終了は
        # transactions.transaction() だけが発行する。
        raw = sqlite3.connect(path, check_same_thread=False, isolation_level=None)
        raw.row_factory = sqlite3.Row
        raw.execute("PRAGMA foreign_keys = ON")
        raw.execute("PRAGMA journal_mode = WAL")
        raw.execute("PRAGMA busy_timeout = 5000")
        return raw

    def substitutions(self) -> dict[str, str]:
        return {
            PK: "INTEGER PRIMARY KEY AUTOINCREMENT",
            TODAY: "date('now', 'localtime')",
            NOW: "datetime('now', 'localtime')",
        }

    def in_transaction(self, raw: Any) -> bool:
        return bool(raw.in_transaction)

    def translate_error(self, error: Exception) -> Exception | None:
        if not isinstance(error, sqlite3.IntegrityError):
            return None
        message = str(error)
        if "UNIQUE" in message.upper():
            return DuplicateKeyError(message)
        if "FOREIGN KEY" in message.upper():
            return ForeignKeyError(message)
        return None


class PostgresDialect(Dialect):
    """サーバー型。複数端末から使う場合や、本番に近い構成で動かす場合に選ぶ。"""

    name = "postgresql"
    placeholder = "%s"
    supports_returning = True

    def __init__(self, dsn: str) -> None:
        self.dsn = dsn

    def connect(self, target: str) -> Any:
        try:
            import psycopg
            from psycopg.rows import dict_row
        except ImportError as error:
            raise RuntimeError(
                'PostgreSQL を使うには追加の依存が必要です: pip install -e ".[postgres]"'
            ) from error
        # autocommit=True にして、開始と終了を transaction() だけが発行する形に
        # そろえる（SQLite 側と同じ扱いにするため）。
        raw = psycopg.connect(target, autocommit=True, row_factory=dict_row)
        raw.execute("SET client_encoding TO 'UTF8'")
        return raw

    def substitutions(self) -> dict[str, str]:
        return {
            PK: "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
            TODAY: "to_char(CURRENT_DATE, 'YYYY-MM-DD')",
            NOW: "to_char(CURRENT_TIMESTAMP, 'YYYY-MM-DD HH24:MI:SS')",
        }

    def in_transaction(self, raw: Any) -> bool:
        import psycopg

        return raw.info.transaction_status != psycopg.pq.TransactionStatus.IDLE

    def translate_error(self, error: Exception) -> Exception | None:
        try:
            import psycopg
        except ImportError:  # pragma: no cover - 依存未導入なら翻訳対象がない
            return None
        if isinstance(error, psycopg.errors.UniqueViolation):
            return DuplicateKeyError(str(error))
        if isinstance(error, psycopg.errors.ForeignKeyViolation):
            return ForeignKeyError(str(error))
        return None


def _swap_placeholders(sql: str, placeholder: str) -> str:
    """文字列リテラルの外にある ? だけを置き換える。"""
    out: list[str] = []
    quote: str | None = None
    for char in sql:
        if quote is None and char in ("'", '"'):
            quote = char
        elif quote is not None and char == quote:
            quote = None
        if char == "?" and quote is None:
            out.append(placeholder)
        else:
            out.append(char)
    return "".join(out)


def resolve(target: str | Path) -> tuple[Dialect, str]:
    """接続先の指定から、方言と接続文字列を決める。

    スキームのない文字列は SQLite のファイルパスとして扱う
    （従来の SHUKATSU_DB の指定をそのまま使えるようにするため）。
    """
    text = str(target)
    parsed = urlparse(text)
    if parsed.scheme in ("postgresql", "postgres"):
        return PostgresDialect(text), text
    if parsed.scheme == "sqlite":
        # sqlite:///relative/path.db と sqlite:////abs/path.db の両方を許す
        return SqliteDialect(), parsed.path.lstrip("/") or parsed.netloc
    if parsed.scheme and len(parsed.scheme) > 1:
        raise ValueError(f"対応していない接続先です: {parsed.scheme}")
    return SqliteDialect(), text


def describe(target: str | Path, base: Path | None = None) -> str:
    """接続先を、画面に出してよい形に要約する。

    接続文字列にはパスワードが、ファイルパスには利用者名やフォルダ構成が
    含まれる。画面共有やスクリーンショットでそのまま漏れるため、
    種別と最小限の識別子だけを返す。
    """
    text = str(target)
    if text.startswith(("postgresql://", "postgres://")):
        return "PostgreSQL（サーバー型）"
    if base is not None:
        try:
            return f"SQLite（{Path(text).relative_to(base).as_posix()}）"
        except ValueError:
            pass
    # Path に任せると、動作中の OS の区切り文字しか見ない。Windows で作った
    # パスを Linux で表示すると分解されず、そのまま出てしまう。
    return f"SQLite（{_last_segment(text)}）"


_SEPARATORS = re.compile(r"[/\\]")


def _last_segment(text: str) -> str:
    """OS に関係なく、パスの最後の要素だけを取り出す。"""
    segments = [part for part in _SEPARATORS.split(text) if part]
    return segments[-1] if segments else text
